import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";
import test from "node:test";
const source=readFileSync(new URL('../server/index.js',import.meta.url),'utf8');
function fixture(){
 const f={decoded:{uid:'u1',email:'test@example.com',firebase:{sign_in_provider:'password'}},user:{isEnabled:true,mobileAccessStatus:'invited',employeeId:'e1',companyId:'c1'},employee:{id:'e1',email:'test@example.com',userCode:'1234',companyId:'c1',mobileAccess:{status:'invited',approvedEmail:'test@example.com'}},writes:[],committed:false};
 const code=source.slice(source.indexOf('function mobileAccessIsApproved('),source.indexOf('const passwordTransition ='));
 const context={admin:{auth:()=>({verifyIdToken:async(token,revoked)=>{assert.equal(revoked,true);return f.decoded;}}),firestore:{FieldValue:{serverTimestamp:()=>123}}},db:{collection:()=>({doc:()=>({get:async()=>({exists:!!f.user,data:()=>f.user})})}),batch:()=>({set:(...args)=>f.writes.push(args),commit:async()=>{f.committed=true;}})},decodedTokenIsAnonymous:d=>d.firebase.sign_in_provider==='anonymous',normaliseEmail:v=>String(v||'').toLowerCase(),normaliseCode:v=>String(v||''),findEmployeeForApprovedUid:async()=>f.employee,employeeIsBlocked:e=>e.isEnabled===false||e.disabled===true||e.active===false||e.archived===true,employeeEmailMatches:(e,email)=>e.email===email,buildSessionData:()=>({companyId:'c1',appAccess:{user:true,service:false}})};
 vm.createContext(context);vm.runInContext(code,context);f.sync=context.syncApprovedEmployeeAuth;return f;
}
test('approved password users activate without replacing their password or role',async()=>{const f=fixture();const result=await f.sync('token');assert.equal(result.employee.mobileAccess.status,'active');assert.equal(f.writes.length,2);assert.equal(f.committed,true);for(const [,payload,options]of f.writes){assert.equal(options.merge,true);assert.equal(Object.hasOwn(payload,'password'),false);assert.equal(Object.hasOwn(payload,'role'),false);}});
test('unapproved, disabled and mismatched identities cannot write session data',async()=>{for(const change of [f=>{f.user=null;},f=>{f.employee=null;},f=>{f.user.mobileAccessStatus='pending';},f=>{f.employee.mobileAccess.status='disabled';},f=>{f.user.disabled=true;},f=>{f.user.appDisabled=true;},f=>{f.employee.isArchived=true;},f=>{f.user.employeeId='other';},f=>{f.user.companyId='other';},f=>{f.decoded.email='other@example.com';},f=>{f.decoded.firebase.sign_in_provider='custom';},f=>{f.decoded.firebase.sign_in_provider='anonymous';}]){const f=fixture();change(f);await assert.rejects(f.sync('token'),e=>e.status===403);assert.equal(f.writes.length,0);}});
test('header authentication is handled before legacy body authentication',()=>{const route=source.slice(source.indexOf('app.post("/auth/sync-employee-auth"'));assert.ok(route.indexOf('syncApprovedEmployeeAuth(headerToken)')<route.indexOf('req.body?.idToken'));assert.match(route,/mobilePasswordTransitions/);});
