import {
  LEGACY_EMPLOYEE_COMPACT_FILES,
  LEGACY_LOCAL_CONTROL_STYLE_FILES,
  LEGACY_LOCAL_PALETTE_FILES,
  LEGACY_STATIC_COLOR_FILES,
  LEGACY_TYPOGRAPHY_STYLE_FILES,
} from "./designSystemLegacyBaseline.js";

export const MIGRATION_BATCHES = {
  1: [
    "app/(protected)/_layout.jsx",
    "app/_layout.jsx",
    "components/app/footer.js",
    "components/app/service-footer.js",
  ],
  2: ["app/(auth)/login.jsx"],
  3: [
    "app/(protected)/screens/homescreen.js",
    "app/(protected)/screens/schedule.js",
    "app/(protected)/me.js",
    "app/(protected)/edit-profile.js",
    "app/(protected)/settings.js",
    "app/(protected)/holidaypage.js",
    "app/(protected)/holiday-request.js",
    "app/(protected)/maintenance.js",
  ],
  4: [
    "app/(protected)/service/index.js",
    "app/(protected)/service/home.js",
    "app/(protected)/service/work.js",
    "app/(protected)/service/service.js",
    "app/(protected)/service/service-list.js",
    "app/(protected)/service/issues.jsx",
    "app/(protected)/service/defects.js",
    "app/(protected)/service/advisories.jsx",
    "app/(protected)/service/equipment-list.js",
    "app/(protected)/service/inspections/index.js",
    "app/(protected)/service/service-history.js",
    "app/(protected)/service/activity-history.jsx",
    "app/(protected)/service/settings.js",
  ],
  5: [
    "app/(protected)/timesheet.js",
    "app/(protected)/week/[id]/index.js",
    "app/(protected)/add-timesheet.js",
    "app/(protected)/vehicle-check.js",
    "app/(protected)/recce-form.js",
    "app/(protected)/vehicle-prep/[id].jsx",
    "app/(protected)/service/book-work.js",
    "app/(protected)/service/defect-form.jsx",
    "app/(protected)/service/repair-form.jsx",
    "app/(protected)/service/inspections/inspection-form/[id].jsx",
    "app/(protected)/service/service-form/[id].jsx",
    "app/(protected)/service/minor-service/[id].jsx",
    "app/(protected)/service/mot-precheck/[id].jsx",
    "app/(protected)/service/tyre-brake-check.jsx",
    "app/(protected)/service/daily-check.jsx",
    "app/(protected)/service/vehicle-prep/[id].jsx",
  ],
  6: [
    "app/(protected)/about.js",
    "app/(protected)/bookings/[id].jsx",
    "app/(protected)/contacts.js",
    "app/(protected)/document-viewer.jsx",
    "app/(protected)/design-system.jsx",
    "app/(protected)/expenses.js",
    "app/(protected)/fix.js",
    "app/(protected)/help.js",
    "app/(protected)/insurance.js",
    "app/(protected)/index.js",
    "app/(protected)/job.js",
    "app/(protected)/notification/[id].js",
    "app/(protected)/notifications.js",
    "app/(protected)/query/[id]/index.js",
    "app/(protected)/receipts.js",
    "app/(protected)/spec-sheets.js",
    "app/(protected)/uploader.js",
    "app/(protected)/vehicles.jsx",
    "app/(protected)/work-diary-board.js",
    "app/(protected)/work-diary.js",
    "app/(protected)/work/index.js",
    "app/(protected)/working-terms.jsx",
    "app/(protected)/service/defects/[id].jsx",
    "app/(protected)/service/design-system.jsx",
    "app/(protected)/service/resolved-defects/[id].jsx",
    "app/(protected)/service/service-form.js",
    "app/(protected)/service/service-history/[vehicleId].jsx",
    "app/(protected)/service/service-record/[id].jsx",
    "app/(protected)/service/vehicle-timeline/[id].jsx",
    "app/(protected)/service/vehicles/[id].jsx",
    "app/(protected)/service/vehicles/file-viewer.jsx",
  ],
};

const routeTests = {
  "app/(protected)/document-viewer.jsx": ["tests/documentViewer.test.js"],
  "app/(protected)/screens/homescreen.js": ["tests/homeLayout.test.js"],
  "app/(protected)/screens/schedule.js": ["tests/scheduleLayout.test.js"],
  "app/(protected)/me.js": ["tests/meLayout.test.js"],
  "app/(protected)/edit-profile.js": ["tests/editProfileLayout.test.js"],
  "app/(protected)/settings.js": ["tests/settingsLayout.test.js"],
  "app/(protected)/holidaypage.js": ["tests/holidayPageLayout.test.js"],
  "app/(protected)/maintenance.js": ["tests/maintenanceReport.test.js"],
  "app/(protected)/contacts.js": ["tests/contactsLayout.test.js"],
  "app/(protected)/expenses.js": ["tests/expensesLayout.test.js"],
  "app/(protected)/receipts.js": ["tests/receiptsLayout.test.js"],
  "app/(protected)/notifications.js": ["tests/notificationsLayout.test.js"],
  "app/(protected)/work-diary.js": ["tests/workDiaryLifecycleAdoption.test.js"],
};

const exceptionSets = {
  compactDensity: LEGACY_EMPLOYEE_COMPACT_FILES,
  localControls: LEGACY_LOCAL_CONTROL_STYLE_FILES,
  localPalette: LEGACY_LOCAL_PALETTE_FILES,
  staticColors: LEGACY_STATIC_COLOR_FILES,
  typography: LEGACY_TYPOGRAPHY_STYLE_FILES,
};

const completedRoutes = new Set([
  "app/(protected)/maintenance.js",
  "app/(protected)/_layout.jsx",
  "app/_layout.jsx",
  "components/app/footer.js",
  "components/app/service-footer.js",
  "app/(auth)/login.jsx",
  "app/(protected)/bookings/[id].jsx",
  "app/(protected)/design-system.jsx",
  "app/(protected)/fix.js",
  "app/(protected)/index.js",
  "app/(protected)/service/service-form.js",
  "app/(protected)/vehicles.jsx",
  "app/(protected)/working-terms.jsx",
  "app/(protected)/about.js",
  "app/(protected)/insurance.js",
  "app/(protected)/help.js",
  "app/(protected)/service/design-system.jsx",
]);

export const DESIGN_SYSTEM_MIGRATION_MANIFEST = Object.entries(MIGRATION_BATCHES)
  .flatMap(([batch, routes]) => routes.map((route) => ({
    route,
    batch: Number(batch),
    status: completedRoutes.has(route) ? "complete" : "pending",
    legacyExceptions: Object.entries(exceptionSets)
      .filter(([, files]) => files.has(route))
      .map(([kind]) => kind),
    tests: routeTests[route] || ["tests/designSystemAdoption.test.js"],
    visualQA: completedRoutes.has(route) ? "reference" : "pending",
  })))
  .sort((a, b) => a.batch - b.batch || a.route.localeCompare(b.route));
